In [2]:
import numpy as np

Imports the numpy module.

In the code, below there is a small comparison between the NumPy array and the standard python list. Both lists work similar to each other.

In [3]:
a = np.array([1,2,3,4,5])
print("--- NumPy Array ---")
print(a)
print(type(a))
print(a[1])
print(a[1:])
print(a[:-2], "\n")

b = [1,2,3,4,5,]
print("--- Standard Array ---")
print(b)
print(type(b))
print(b[1])
print(b[1:])
print(b[:-2])

--- NumPy Array ---
[1 2 3 4 5]
<class 'numpy.ndarray'>
2
[2 3 4 5]
[1 2 3] 

--- Standard Array ---
[1, 2, 3, 4, 5]
<class 'list'>
2
[2, 3, 4, 5]
[1, 2, 3]


NumPy can be used to create multidimensional arrays.

In [10]:
np_2d=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
np_cast=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]], dtype="<U7")# (dtype) Allows to dynamically cast a variable
print(np_2d[0])
print(np_2d[0][1])

[1 2 3]
2


In [11]:
print(np_2d.shape) # Displays the dimensions
print(np_2d.ndim) # Displays depth of dimensions
print(np_2d.size) # Displays number of elements
print(np_2d.dtype) # Displays data type
print(np_cast.dtype)

(3, 3)
2
9
int32
<U7


NumPy Documentation: https://numpy.org/doc/

In [13]:
a = np.full((2,3,4), 9) # Parameters of dimensions, value
print(a)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]
