In [2]:
import numpy as np

Imports the numpy module.

In the code, below there is a small comparison between the NumPy array and the standard python list. Both lists work similar to each other.

In [5]:
a = np.array([1,2,3,4,5])
print("--- NumPy Array ---")
print(a)
print(type(a))
print(a[1])
print(a[1:])
print(a[:-2], "\n")

b = [1,2,3,4,5,]
print("--- Standard Array ---")
print(b)
print(type(b))
print(b[1])
print(b[1:])
print(b[:-2])

--- NumPy Array ---
[1 2 3 4 5]
<class 'numpy.ndarray'>
2
[2 3 4 5]
[1 2 3] 

--- Standard Array ---
[1, 2, 3, 4, 5]
<class 'list'>
2
[2, 3, 4, 5]
[1, 2, 3]


NumPy can be used to create multidimensional arrays.

In [ ]:
np_2d=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])